Stack: code/source/Testa_Nlinhas.c File Reference
Testa_Nlinhas.c File Reference
#include <gtest/gtest.h>
#include "Nlinhas.h"
Macros
#define StackSizeNull 0
#define StackSizeNegative -10
#define StackSizePositive 20
#define StackElement 675
Functions
int main (int argc, char **argv)
TEST (Stack, CreateStackSizeNull)
TEST (Stack, CreateStackSizeNegative)
TEST (Stack, CreateStackSizePositive)
TEST (Stack, PushEmptyStack)
TEST (Stack, PushFullStack)
TEST (Stack, PopEmptyStack)
TEST (Stack, PopFullStack)
TEST (Stack, TopEmptyStack)
TEST (Stack, TopFullStack)
TEST (Stack, SizeStack)
TEST (Stack, SetSizeNegativeStack)
TEST (Stack, SetSizePositiveStack)
TEST (Stack, IsFullStack)
TEST (Stack, IsNotFullStack)
TEST (Stack, IsEmptyStack)
TEST (Stack, IsNotEmptyStack)
TEST (Stack, DestroyStack)
Macro Definition Documentation
StackElement
#define StackElement 675
Definition at line 7 of file Testa_Nlinhas.c.
Referenced by TEST().
StackSizeNegative
#define StackSizeNegative -10
Definition at line 5 of file Testa_Nlinhas.c.
Referenced by TEST().
StackSizeNull
#define StackSizeNull 0
Definition at line 4 of file Testa_Nlinhas.c.
Referenced by TEST().
StackSizePositive
#define StackSizePositive 20
Definition at line 6 of file Testa_Nlinhas.c.
Referenced by TEST().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 9 of file Testa_Nlinhas.c.
{
     ::testing::InitGoogleTest(&argc, argv);
     return RUN_ALL_TESTS();
 }
TEST() [1/17]
TEST (Stack , CreateStackSizeNull)
Definition at line 14 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), Size(), and StackSizeNull.
{
     Structure_Stack * stack = CreateStack(StackSizeNull);
     ASSERT_EQ(StackSizeNull, Size(stack));
     DestroyStack(stack);
 }
TEST() [2/17]
TEST (Stack , CreateStackSizeNegative)
Definition at line 19 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), Size(), and StackSizeNegative.
{
     Structure_Stack * stack = CreateStack(StackSizeNegative);
     ASSERT_NE(StackSizeNegative, Size(stack));
     DestroyStack(stack);
 }
TEST() [3/17]
TEST (Stack , CreateStackSizePositive)
Definition at line 25 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), Size(), and StackSizePositive.
{
     Structure_Stack * stack = CreateStack(StackSizePositive);
     ASSERT_EQ(StackSizePositive, Size(stack));
     DestroyStack(stack);
 }
TEST() [4/17]
TEST (Stack , PushEmptyStack)
Definition at line 31 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsEmpty(), ItemType::Item, Push(), StackElement, and StackSizePositive.
{
     Structure_Stack * stack = CreateStack(StackSizePositive);
     ItemType Element;
     Element.Item = StackElement;
     Push(stack, Element);
     EXPECT_FALSE(IsEmpty(stack));
     DestroyStack(stack);
 }
TEST() [5/17]
TEST (Stack , PushFullStack)
Definition at line 39 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), ItemType::Item, Pop(), and Push().
{
     Structure_Stack* stack = CreateStack(1);
     ItemType Element;
     Element.Item = 100;
     Push(stack, Element);
     Element.Item+=50;
     Push(stack, Element);
     EXPECT_NE(Element.Item, Pop(stack).Item);
     DestroyStack(stack);
 }
TEST() [6/17]
TEST (Stack , PopEmptyStack)
Definition at line 50 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), Pop(), and Top().
{
     Structure_Stack* stack = CreateStack(1);
     EXPECT_EQ(Top(stack),Pop(stack).Item);
     DestroyStack(stack);
 }
TEST() [7/17]
TEST (Stack , PopFullStack)
Definition at line 55 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsFull(), ItemType::Item, Pop(), Push(), StackElement, and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     ItemType Element;
     Element.Item = StackElement;
     while(!IsFull(stack))
     {
        Element.Item += 5;
        Push(stack, Element);
     }
     EXPECT_EQ(Element.Item, Pop(stack).Item);
     DestroyStack(stack);
 }
TEST() [8/17]
TEST (Stack , TopEmptyStack)
Definition at line 68 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), StackSizePositive, and Top().
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     EXPECT_TRUE(Top(stack));
     DestroyStack(stack);
 }
TEST() [9/17]
TEST (Stack , TopFullStack)
Definition at line 73 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsFull(), ItemType::Item, Push(), Size(), StackElement, StackSizePositive, and Top().
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     ItemType Element;
     Element.Item = StackElement;
     while(!IsFull(stack))
     {
        Push(stack, Element);
     }
     EXPECT_EQ(Size(stack)-1,Top(stack));
     DestroyStack(stack);
 }
TEST() [10/17]
TEST (Stack , SizeStack)
Definition at line 85 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), Size(), and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     EXPECT_EQ(StackSizePositive, Size(stack));
     DestroyStack(stack);
 }
TEST() [11/17]
TEST (Stack , SetSizeNegativeStack)
Definition at line 91 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), SetSize(), Size(), StackSizeNegative, and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     EXPECT_EQ(StackSizePositive, Size(stack));
     SetSize(stack,StackSizeNegative);
     EXPECT_NE(StackSizeNegative, Size(stack));
     DestroyStack(stack);
 }
TEST() [12/17]
TEST (Stack , SetSizePositiveStack)
Definition at line 98 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), SetSize(), Size(), and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     EXPECT_EQ(StackSizePositive, Size(stack));
     SetSize(stack,10);
     EXPECT_EQ(10, Size(stack));
     DestroyStack(stack);
 }
TEST() [13/17]
TEST (Stack , IsFullStack)
Definition at line 106 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsFull(), ItemType::Item, Push(), StackElement, and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     ItemType Element;
     Element.Item = StackElement;
     while(!IsFull(stack))
     {
        Push(stack, Element);
     }
     EXPECT_TRUE(IsFull(stack));
     DestroyStack(stack);
 }
TEST() [14/17]
TEST (Stack , IsNotFullStack)
Definition at line 117 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsFull(), ItemType::Item, Pop(), Push(), StackElement, and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     ItemType Element;
     Element.Item = StackElement;
     while(!IsFull(stack))
     {
        Push(stack, Element);
     }
     Pop(stack);
     EXPECT_FALSE(IsFull(stack));
     DestroyStack(stack);
 }
TEST() [15/17]
TEST (Stack , IsEmptyStack)
Definition at line 130 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsEmpty(), and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     EXPECT_TRUE(IsEmpty(stack));
     DestroyStack(stack);
 }
TEST() [16/17]
TEST (Stack , IsNotEmptyStack)
Definition at line 135 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), IsEmpty(), IsFull(), ItemType::Item, Push(), StackElement, and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     ItemType Element;
     Element.Item = StackElement;
     while(!IsFull(stack))
     {
        Push(stack, Element);
     }
     EXPECT_FALSE(IsEmpty(stack));
     DestroyStack(stack);
 }
TEST() [17/17]
TEST (Stack , DestroyStack)
Definition at line 147 of file Testa_Nlinhas.c.
References CreateStack(), DestroyStack(), and StackSizePositive.
{
     Structure_Stack* stack = CreateStack(StackSizePositive);
     DestroyStack(stack);
     EXPECT_TRUE(stack);
 }