Stack: code/include/Nlinhas.h File Reference
Nlinhas.h File Reference
Data Structures
struct ItemType
struct Structure_Stack
Typedefs
typedef struct ItemType ItemType
Functions
void Push (Structure_Stack *Stack, ItemType Element)
ItemType Pop (Structure_Stack *Stack)
int Top (Structure_Stack *Stack)
int Size (Structure_Stack *Stack)
void SetSize (Structure_Stack *Stack, int SizeStack)
int IsFull (Structure_Stack *Stack)
int IsEmpty (Structure_Stack *Stack)
Structure_Stack * CreateStack (int SizeStack)
void DestroyStack (Structure_Stack *Stack)
Typedef Documentation
ItemType
typedef struct ItemType ItemType
Function Documentation
CreateStack()
Structure_Stack* CreateStack (int SizeStack)
Definition at line 53 of file Nlinhas.c.
References Structure_Stack::DataStack, EMPTY, Structure_Stack::SizeStack, and Structure_Stack::TopStack.
Referenced by TEST().
 {
     if(SizeStack < 0)
         SizeStack = 0;
     Structure_Stack* stack = (Structure_Stack *) malloc(sizeof(Structure_Stack));
     stack->DataStack = (ItemType *) malloc(SizeStack*sizeof(ItemType));
     stack->TopStack = EMPTY;
     stack->SizeStack = SizeStack;
     return stack;
 }
DestroyStack()
void DestroyStack (Structure_Stack * Stack)
Definition at line 64 of file Nlinhas.c.
References Structure_Stack::DataStack.
Referenced by TEST().
 {
     free(Stack->DataStack);
     free(Stack);
 }
IsEmpty()
int IsEmpty (Structure_Stack * Stack)
Definition at line 48 of file Nlinhas.c.
References EMPTY, and Top().
Referenced by Pop(), and TEST().
 {
     return Top(Stack) == EMPTY;
 }
IsFull()
int IsFull (Structure_Stack * Stack)
Definition at line 43 of file Nlinhas.c.
References Size(), and Top().
Referenced by Push(), and TEST().
 {
     return Top(Stack) == Size(Stack)-1;
 }
Pop()
ItemType Pop (Structure_Stack * Stack)
Definition at line 13 of file Nlinhas.c.
References Structure_Stack::DataStack, IsEmpty(), ItemType::Item, and Structure_Stack::TopStack.
Referenced by TEST().
 {
     if(!IsEmpty(Stack))
     {
         return Stack->DataStack[Stack->TopStack--];
     }
     ItemType error;
     error.Item = -1;
     return error;
 }
Push()
void Push (Structure_Stack * Stack, ItemType Element)
Definition at line 7 of file Nlinhas.c.
References Structure_Stack::DataStack, IsFull(), and Structure_Stack::TopStack.
Referenced by TEST().
 {
     if(!IsFull(Stack))
         Stack->DataStack[++Stack->TopStack] = Element;
 }
SetSize()
void SetSize (Structure_Stack * Stack, int SizeStack)
Definition at line 34 of file Nlinhas.c.
References Structure_Stack::DataStack, EMPTY, and Structure_Stack::SizeStack.
Referenced by TEST().
 {
     if(SizeStack > EMPTY)
     {
         Stack->DataStack = (ItemType *)realloc(Stack->DataStack, SizeStack*sizeof(ItemType));
         Stack->SizeStack = SizeStack;
     }
 }
Size()
int Size (Structure_Stack * Stack)
Definition at line 29 of file Nlinhas.c.
References Structure_Stack::SizeStack.
Referenced by IsFull(), and TEST().
 {
     return Stack->SizeStack;
 }
Top()
int Top (Structure_Stack * Stack)
Definition at line 24 of file Nlinhas.c.
References Structure_Stack::TopStack.
Referenced by IsEmpty(), IsFull(), and TEST().
 {
     return Stack->TopStack;
 }